return {
    --- Diagnostic severities.
    diagnostics = {
        ERROR = "",
        WARN = "",
        HINT = "",
        INFO = "",
    },

    --- For folding.
    arrows = {
        right = "",
        left = "",
        up = "",
        down = "",
    },

    --- LSP symbol kinds.
    symbol_kinds = {
        Array = "󰅪",
        Class = "",
        Color = "󰏘",
        Constant = "󰏿",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "󰜢",
        File = "󰈙",
        Folder = "󰉋",
        Function = "󰆧",
        Interface = "",
        Keyword = "󰌋",
        Method = "󰆧",
        Module = "",
        Operator = "󰆕",
        Property = "󰜢",
        Reference = "󰈇",
        Snippet = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "󰀫",
        Codeium = "󰚩 ",
        Copilot = " ",
        LazyDev = "b ",
    },

    --- Shared icons that don't really fit into a category.
    misc = {
        bug = "",
        dashed_bar = "┊",
        ellipsis = "…",
        git = "",
        palette = "󰏘",
        robot = "󰚩",
        search = "",
        terminal = "",
        toolbox = "󰦬",
        vertical_bar = "│",
    },
    ui = {
        ChevronRight = "",
        ChevronShortRight = "",
    },
}
-- {
--                 mode = "symbol_text",
--                 symbol_map = {
--                     Array = " ",
--                     Boolean = " ",
--                     Class = " ",
--                     Color = " ",
--                     Constant = " ",
--                     Constructor = " ",
--                     Enum = " ",
--                     EnumMember = " ",
--                     Event = " ",
--                     Field = " ",
--                     File = " ",
--                     Folder = "󰉋 ",
--                     Function = " ",
--                     Interface = " ",
--                     Key = " ",
--                     Keyword = " ",
--                     Method = " ",
--                     -- Module = " ",
--                     Module = " ",
--                     Namespace = " ",
--                     Null = "󰟢",
--                     Number = " ",
--                     Object = " ",
--                     Operator = " ",
--                     Package = " ",
--                     Property = " ",
--                     Reference = " ",
--                     Snippet = " ",
--                     String = " ",
--                     Struct = " ",
--                     Text = " ",
--                     TypeParameter = " ",
--                     Unit = " ",
--                     Value = " ",
--                     Variable = " ",
--                     Codeium = "󰚩 ",
--                     Copilot = " ",
--                     LazyDev = "b ",
--                 },
--             }

-- Old icons
--
-- return {
--     kind = {
--         Array = " ",
--         Boolean = " ",
--         Class = " ",
--         Color = " ",
--         Constant = " ",
--         Constructor = " ",
--         Enum = " ",
--         EnumMember = " ",
--         Event = " ",
--         Field = " ",
--         File = " ",
--         Folder = "󰉋 ",
--         Function = " ",
--         Interface = " ",
--         Key = " ",
--         Keyword = " ",
--         Method = " ",
--         -- Module = " ",
--         Module = " ",
--         Namespace = " ",
--         Null = "󰟢 ",
--         Number = " ",
--         Object = " ",
--         Operator = " ",
--         Package = " ",
--         Property = " ",
--         Reference = " ",
--         Snippet = " ",
--         String = " ",
--         Struct = " ",
--         Text = " ",
--         TypeParameter = " ",
--         Unit = " ",
--         Value = " ",
--         Variable = " ",
--     },
--     git = {
--         LineAdded = " ",
--         LineModified = " ",
--         LineRemoved = " ",
--         FileDeleted = " ",
--         FileIgnored = "◌",
--         FileRenamed = " ",
--         FileStaged = "S",
--         FileUnmerged = "",
--         FileUnstaged = "",
--         FileUntracked = "U",
--         Diff = " ",
--         Repo = " ",
--         Octoface = " ",
--         Copilot = " ",
--         Branch = "",
--     },
--     ui = {
--         ArrowCircleDown = "",
--         ArrowCircleLeft = "",
--         ArrowCircleRight = "",
--         ArrowCircleUp = "",
--         BoldArrowDown = "",
--         BoldArrowLeft = "",
--         BoldArrowRight = "",
--         BoldArrowUp = "",
--         BoldClose = "",
--         BoldDividerLeft = "",
--         BoldDividerRight = "",
--         BoldLineLeft = "▎",
--         BoldLineMiddle = "┃",
--         BoldLineDashedMiddle = "┋",
--         BookMark = "",
--         BoxChecked = " ",
--         Bug = " ",
--         Stacks = "",
--         Scopes = "",
--         Watches = "󰂥",
--         DebugConsole = " ",
--         Calendar = " ",
--         Check = "",
--         ChevronRight = "",
--         ChevronShortDown = "",
--         ChevronShortLeft = "",
--         ChevronShortRight = "",
--         ChevronShortUp = "",
--         Circle = " ",
--         Close = "󰅖",
--         CloudDownload = " ",
--         Code = "",
--         Comment = "",
--         Dashboard = "",
--         DividerLeft = "",
--         DividerRight = "",
--         DoubleChevronRight = "»",
--         Ellipsis = "",
--         EmptyFolder = " ",
--         EmptyFolderOpen = " ",
--         File = " ",
--         FileSymlink = "",
--         Files = " ",
--         FindFile = "󰈞",
--         FindText = "󰊄",
--         Fire = "",
--         Folder = "󰉋 ",
--         FolderOpen = " ",
--         FolderSymlink = " ",
--         Forward = " ",
--         Gear = " ",
--         History = " ",
--         Lightbulb = " ",
--         LineLeft = "▏",
--         LineMiddle = "│",
--         List = " ",
--         Lock = " ",
--         NewFile = " ",
--         Note = " ",
--         Package = " ",
--         Pencil = "󰏫 ",
--         Plus = " ",
--         Project = " ",
--         Search = " ",
--         SignIn = " ",
--         SignOut = " ",
--         Tab = "󰌒 ",
--         Table = " ",
--         Target = "󰀘 ",
--         Telescope = " ",
--         Text = " ",
--         Tree = "",
--         Triangle = "󰐊",
--         TriangleShortArrowDown = "",
--         TriangleShortArrowLeft = "",
--         TriangleShortArrowRight = "",
--         TriangleShortArrowUp = "",
--     },
--     diagnostics = {
--         BoldError = "",
--         Error = "",
--         BoldWarning = "",
--         Warning = "",
--         BoldInformation = "",
--         Information = "",
--         BoldQuestion = "",
--         Question = "",
--         BoldHint = "",
--         Hint = "󰌶",
--         Debug = "",
--         Trace = "✎",
--     },
--     misc = {
--         Robot = "󰚩 ",
--         Squirrel = " ",
--         Tag = " ",
--         Watch = "",
--         Smiley = " ",
--         Package = " ",
--         CircuitBoard = " ",
--     },
-- }
--
--
--
